FROM python:3.12.6-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /code

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY src/ /code/

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "my_project.wsgi"]
