version: "3.9"

services:
  db:
    container_name: romashka-db
    build:
      dockerfile: Dockerfile.prod
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    container_name: romashka-web
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data:
